export const districtsAndUpazilas: Record<
  string,
  { value: string; upazilas: { title: string; value: string }[] }
> = {
  // Barishal Division
  বরিশাল: {
    value: "barishal",
    upazilas: [
      { title: "আগৈলঝাড়া", value: "agailjhara" },
      { title: "বাবুগঞ্জ", value: "babuganj" },
      { title: "বাকেরগঞ্জ", value: "bakerganj" },
      { title: "বানারীপাড়া", value: "banaripara" },
      { title: "গৌরনদী", value: "gaurnadi" },
      { title: "হিজলা", value: "hizla" },
      { title: "বরিশাল সদর", value: "barishal-sadar" },
      { title: "মেহেন্দিগঞ্জ", value: "mehendiganj" },
      { title: "মুলাদী", value: "muladi" },
      { title: "উজিরপুর", value: "wazirpur" },
    ],
  },
  ভোলা: {
    value: "bhola",
    upazilas: [
      { title: "ভোলা সদর", value: "bhola-sadar" },
      { title: "বোরহানউদ্দিন", value: "borhanuddin" },
      { title: "চরফ্যাশন", value: "charfasson" },
      { title: "দৌলতখান", value: "daulatkhan" },
      { title: "লালমোহন", value: "lalmohan" },
      { title: "মনপুরা", value: "manpura" },
      { title: "তজুমদ্দিন", value: "tazumuddin" },
    ],
  },
  ঝালকাঠি: {
    value: "jhalokati",
    upazilas: [
      { title: "ঝালকাঠি সদর", value: "jhalokati-sadar" },
      { title: "কাঠালিয়া", value: "kathalia" },
      { title: "নলছিটি", value: "nalchity" },
      { title: "রাজাপুর", value: "rajapur" },
    ],
  },
  পটুয়াখালী: {
    value: "patuakhali",
    upazilas: [
      { title: "বাউফল", value: "bauphal" },
      { title: "দশমিনা", value: "dashmina" },
      { title: "গলাচিপা", value: "galachipa" },
      { title: "কলাপাড়া", value: "kalapara" },
      { title: "মির্জাগঞ্জ", value: "mirzaganj" },
      { title: "পটুয়াখালী সদর", value: "patuakhali-sadar" },
      { title: "রাঙ্গাবালী", value: "rangabali" },
      { title: "দুমকি", value: "dumki" },
    ],
  },
  পিরোজপুর: {
    value: "pirojpur",
    upazilas: [
      { title: "ভান্ডারিয়া", value: "bhandaria" },
      { title: "কাউখালী", value: "kaukhali" },
      { title: "মঠবাড়িয়া", value: "mathbaria" },
      { title: "নাজিরপুর", value: "nazirpur" },
      { title: "নেসারাবাদ", value: "nesarabad" },
      { title: "পিরোজপুর সদর", value: "pirojpur-sadar" },
      { title: "ইন্দুরকানী", value: "indurkani" },
    ],
  },
  বরগুনা: {
    value: "barguna",
    upazilas: [
      { title: "আমতলী", value: "amtali" },
      { title: "বরগুনা সদর", value: "barguna-sadar" },
      { title: "বেতাগী", value: "betagi" },
      { title: "বামনা", value: "bamna" },
      { title: "পাথরঘাটা", value: "patharghata" },
      { title: "তালতলী", value: "taltali" },
    ],
  },

  // Chattogram Division
  চট্টগ্রাম: {
    value: "chattogram",
    upazilas: [
      { title: "আনোয়ারা", value: "anowara" },
      { title: "বাঁশখালী", value: "banshkhali" },
      { title: "বোয়ালখালী", value: "boalkhali" },
      { title: "চন্দনাইশ", value: "chandanaish" },
      { title: "ফটিকছড়ি", value: "fatikchhari" },
      { title: "হাটহাজারী", value: "hathazari" },
      { title: "লোহাগাড়া", value: "lohagara" },
      { title: "মিরসরাই", value: "mirsharai" },
      { title: "পটিয়া", value: "patiya" },
      { title: "রাঙ্গুনিয়া", value: "rangunia" },
      { title: "রাউজান", value: "raozan" },
      { title: "সন্দ্বীপ", value: "sandwip" },
      { title: "সাতকানিয়া", value: "satkania" },
      { title: "সীতাকুণ্ড", value: "sitakunda" },
    ],
  },
  কুমিল্লা: {
    value: "cumilla",
    upazilas: [
      { title: "দেবিদ্বার", value: "debidwar" },
      { title: "বরুড়া", value: "barura" },
      { title: "ব্রাহ্মণপাড়া", value: "brahmanpara" },
      { title: "চান্দিনা", value: "chandina" },
      { title: "চৌদ্দগ্রাম", value: "chauddagram" },
      { title: "দাউদকান্দি", value: "daudkandi" },
      { title: "হোমনা", value: "homna" },
      { title: "লাকসাম", value: "laksam" },
      { title: "মুরাদনগর", value: "muradnagar" },
      { title: "নাঙ্গলকোট", value: "nangalkot" },
      { title: "কুমিল্লা সদর", value: "cumilla-sadar" },
      { title: "মেঘনা", value: "meghna" },
      { title: "মনোহরগঞ্জ", value: "manoharganj" },
      { title: "তিতাস", value: "titas" },
      { title: "বুড়িচং", value: "burichong" },
      { title: "লালমাই", value: "lalmai" },
    ],
  },
  ফেনী: {
    value: "feni",
    upazilas: [
      { title: "ছাগলনাইয়া", value: "chhagalnaiya" },
      { title: "দাগনভূঞা", value: "daganbhuiyan" },
      { title: "ফেনী সদর", value: "feni-sadar" },
      { title: "ফুলগাজী", value: "fulgazi" },
      { title: "পরশুরাম", value: "parshuram" },
      { title: "সোনাগাজী", value: "sonagazi" },
    ],
  },
  ব্রাহ্মণবাড়িয়া: {
    value: "brahmanbaria",
    upazilas: [
      { title: "আশুগঞ্জ", value: "ashuganj" },
      { title: "বাঞ্ছারামপুর", value: "bancharampur" },
      { title: "ব্রাহ্মণবাড়িয়া সদর", value: "brahmanbaria-sadar" },
      { title: "বিজয়নগর", value: "bijoynagar" },
      { title: "কসবা", value: "kasba" },
      { title: "নবীনগর", value: "nabinagar" },
      { title: "নাসিরনগর", value: "nasirnagar" },
      { title: "সরাইল", value: "sarail" },
      { title: "আখাউড়া", value: "akhaura" },
    ],
  },
  রাঙ্গামাটি: {
    value: "rangamati",
    upazilas: [
      { title: "বাঘাইছড়ি", value: "baghaichhari" },
      { title: "বরকল", value: "barkal" },
      { title: "বিলাইছড়ি", value: "belaichhari" },
      { title: "জুরাছড়ি", value: "jurachhari" },
      { title: "কাউখালী", value: "kaukhali" },
      { title: "লংগদু", value: "langadu" },
      { title: "নানিয়ারচর", value: "naniarchar" },
      { title: "রাজস্থলী", value: "rajasthali" },
      { title: "রাঙ্গামাটি সদর", value: "rangamati-sadar" },
    ],
  },
  নোয়াখালী: {
    value: "noakhali",
    upazilas: [
      { title: "বেগমগঞ্জ", value: "begumganj" },
      { title: "চাটখিল", value: "chatkhil" },
      { title: "কোম্পানীগঞ্জ", value: "companionganj" },
      { title: "হাতিয়া", value: "hatia" },
      { title: "নোয়াখালী সদর", value: "noakhali-sadar" },
      { title: "সেনবাগ", value: "senbagh" },
      { title: "সোনাইমুড়ি", value: "sonaimuri" },
      { title: "সুবর্ণচর", value: "subarnachar" },
      { title: "কবিরহাট", value: "kabirhat" },
    ],
  },
  চাঁদপুর: {
    value: "chandpur",
    upazilas: [
      { title: "চাঁদপুর সদর", value: "chandpur-sadar" },
      { title: "ফরিদগঞ্জ", value: "faridganj" },
      { title: "হাইমচর", value: "haimchar" },
      { title: "হাজীগঞ্জ", value: "haziganj" },
      { title: "কচুয়া", value: "kachua" },
      { title: "মতলব উত্তর", value: "matlab-uttar" },
      { title: "মতলব দক্ষিণ", value: "matlab-dakshin" },
      { title: "শাহরাস্তি", value: "shahrasti" },
    ],
  },
  লক্ষ্মীপুর: {
    value: "lakshmipur",
    upazilas: [
      { title: "লক্ষ্মীপুর সদর", value: "lakshmipur-sadar" },
      { title: "রামগঞ্জ", value: "ramganj" },
      { title: "রামগতি", value: "ramgati" },
      { title: "রায়পুর", value: "raipur" },
      { title: "কমলনগর", value: "kamalnagar" },
    ],
  },
  কক্সবাজার: {
    value: "coxsbazar",
    upazilas: [
      { title: "চকরিয়া", value: "chakaria" },
      { title: "কক্সবাজার সদর", value: "coxsbazar-sadar" },
      { title: "কুতুবদিয়া", value: "kutubdia" },
      { title: "মহেশখালী", value: "maheshkhali" },
      { title: "রামু", value: "ramu" },
      { title: "টেকনাফ", value: "teknaf" },
      { title: "উখিয়া", value: "ukhiya" },
      { title: "পেকুয়া", value: "pekua" },
      { title: "ঈদগাঁও", value: "eidgaon" },
    ],
  },
  খাগড়াছড়ি: {
    value: "khagrachhari",
    upazilas: [
      { title: "দিঘিনালা", value: "dighinala" },
      { title: "খাগড়াছড়ি সদর", value: "khagrachhari-sadar" },
      { title: "লক্ষ্মীছড়ি", value: "lakshmichhari" },
      { title: "মহালছড়ি", value: "mahalchhari" },
      { title: "মানিকছড়ি", value: "manikchhari" },
      { title: "মাটিরাঙ্গা", value: "matiranga" },
      { title: "পানছড়ি", value: "panchhari" },
      { title: "রামগড়", value: "ramgarh" },
    ],
  },
  বান্দরবান: {
    value: "bandarban",
    upazilas: [
      { title: "আলীকদম", value: "alikadam" },
      { title: "বান্দরবান সদর", value: "bandarban-sadar" },
      { title: "লামা", value: "lama" },
      { title: "নাইক্ষ্যংছড়ি", value: "naikhongchhari" },
      { title: "রোয়াংছড়ি", value: "rowangchhari" },
      { title: "রুমা", value: "ruma" },
      { title: "থানচি", value: "thanchi" },
    ],
  },

  // Dhaka Division
  ঢাকা: {
    value: "dhaka",
    upazilas: [
      { title: "দোহার", value: "dohar" },
      { title: "কেরানীগঞ্জ", value: "keraniganj" },
      { title: "নবাবগঞ্জ", value: "nawabganj" },
      { title: "সাভার", value: "savar" },
      { title: "ধামরাই", value: "dhamrai" },
    ],
  },
  ফরিদপুর: {
    value: "faridpur",
    upazilas: [
      { title: "আলফাডাঙ্গা", value: "alfadanga" },
      { title: "ভাঙ্গা", value: "bhanga" },
      { title: "বোয়ালমারী", value: "boalmari" },
      { title: "চরভদ্রাসন", value: "charbhadrasan" },
      { title: "ফরিদপুর সদর", value: "faridpur-sadar" },
      { title: "মধুখালী", value: "madhukhali" },
      { title: "নগরকান্দা", value: "nagarkanda" },
      { title: "সদরপুর", value: "sadarpur" },
      { title: "সালথা", value: "saltha" },
    ],
  },
  গাজীপুর: {
    value: "gazipur",
    upazilas: [
      { title: "গাজীপুর সদর", value: "gazipur-sadar" },
      { title: "কালীগঞ্জ", value: "kaliganj" },
      { title: "কালিয়াকৈর", value: "kaliakair" },
      { title: "কাপাসিয়া", value: "kapasia" },
      { title: "শ্রীপুর", value: "sreepur" },
    ],
  },
  গোপালগঞ্জ: {
    value: "gopalganj",
    upazilas: [
      { title: "গোপালগঞ্জ সদর", value: "gopalganj-sadar" },
      { title: "কাশিয়ানী", value: "kashiani" },
      { title: "কোটালীপাড়া", value: "kotalipara" },
      { title: "মুকসুদপুর", value: "muksudpur" },
      { title: "টুঙ্গিপাড়া", value: "tungipara" },
    ],
  },
  কিশোরগঞ্জ: {
    value: "kishoreganj",
    upazilas: [
      { title: "অষ্টগ্রাম", value: "austagram" },
      { title: "বাজিতপুর", value: "bajitpur" },
      { title: "ভৈরব", value: "bhairab" },
      { title: "হোসেনপুর", value: "hossainpur" },
      { title: "ইটনা", value: "itna" },
      { title: "করিমগঞ্জ", value: "karimganj" },
      { title: "কটিয়াদী", value: "katiadi" },
      { title: "কিশোরগঞ্জ সদর", value: "kishoreganj-sadar" },
      { title: "কুলিয়ারচর", value: "kuliarchar" },
      { title: "মিঠামইন", value: "mithamain" },
      { title: "নিকলী", value: "nikli" },
      { title: "পাকুন্দিয়া", value: "pakundia" },
      { title: "তাড়াইল", value: "tarail" },
    ],
  },
  মাদারীপুর: {
    value: "madaripur",
    upazilas: [
      { title: "কালকিনি", value: "kalkini" },
      { title: "মাদারীপুর সদর", value: "madaripur-sadar" },
      { title: "রাজৈর", value: "rajair" },
      { title: "শিবচর", value: "shibchar" },
      { title: "দশর", value: "dasar" },
    ],
  },
  মানিকগঞ্জ: {
    value: "manikganj",
    upazilas: [
      { title: "দৌলতপুর", value: "daulatpur" },
      { title: "ঘিওর", value: "ghior" },
      { title: "হরিরামপুর", value: "harirampur" },
      { title: "মানিকগঞ্জ সদর", value: "manikganj-sadar" },
      { title: "সাটুরিয়া", value: "saturia" },
      { title: "শিবালয়", value: "shivalaya" },
      { title: "সিংগাইর", value: "singair" },
    ],
  },
  মুন্সীগঞ্জ: {
    value: "munshiganj",
    upazilas: [
      { title: "গজারিয়া", value: "gazaria" },
      { title: "লৌহজং", value: "lauhajang" },
      { title: "মুন্সীগঞ্জ সদর", value: "munshiganj-sadar" },
      { title: "সিরাজদিখান", value: "sirajdikhan" },
      { title: "শ্রীনগর", value: "sreenagar" },
      { title: "টঙ্গিবাড়ী", value: "tongibari" },
    ],
  },
  নারায়ণগঞ্জ: {
    value: "narayanganj",
    upazilas: [
      { title: "আড়াইহাজার", value: "araihazar" },
      { title: "বন্দর", value: "bandar" },
      { title: "নারায়ণগঞ্জ সদর", value: "narayanganj-sadar" },
      { title: "রূপগঞ্জ", value: "rupganj" },
      { title: "সোনারগাঁ", value: "sonargaon" },
    ],
  },
  নরসিংদী: {
    value: "narsingdi",
    upazilas: [
      { title: "বেলাবো", value: "belabo" },
      { title: "মনোহরদী", value: "monohardi" },
      { title: "নরসিংদী সদর", value: "narsingdi-sadar" },
      { title: "পলাশ", value: "palash" },
      { title: "রায়পুরা", value: "raipura" },
      { title: "শিবপুর", value: "shibpur" },
    ],
  },
  রাজবাড়ী: {
    value: "rajbari",
    upazilas: [
      { title: "বালিয়াকান্দি", value: "baliakandi" },
      { title: "গোয়ালন্দ", value: "goalandaghat" },
      { title: "পাংশা", value: "pangsha" },
      { title: "রাজবাড়ী সদর", value: "rajbari-sadar" },
      { title: "কালুখালী", value: "kalukhali" },
    ],
  },
  শরীয়তপুর: {
    value: "shariatpur",
    upazilas: [
      { title: "ভেদরগঞ্জ", value: "bhedarganj" },
      { title: "ডামুড্যা", value: "damudya" },
      { title: "গোসাইরহাট", value: "gosairhat" },
      { title: "নড়িয়া", value: "naria" },
      { title: "শরীয়তপুর সদর", value: "shariatpur-sadar" },
      { title: "জাজিরা", value: "zajira" },
    ],
  },
  টাঙ্গাইল: {
    value: "tangail",
    upazilas: [
      { title: "বাসাইল", value: "basail" },
      { title: "ভূঞাপুর", value: "bhuapur" },
      { title: "দেলদুয়ার", value: "delduar" },
      { title: "ধনবাড়ী", value: "dhanbari" },
      { title: "ঘাটাইল", value: "ghatail" },
      { title: "গোপালপুর", value: "gopalpur" },
      { title: "কালিহাতী", value: "kalihati" },
      { title: "মধুপুর", value: "madhupur" },
      { title: "মির্জাপুর", value: "mirzapur" },
      { title: "নাগরপুর", value: "nagarpur" },
      { title: "সখীপুর", value: "sakhipur" },
      { title: "টাঙ্গাইল সদর", value: "tangail-sadar" },
    ],
  },

  // Khulna Division
  খুলনা: {
    value: "khulna",
    upazilas: [
      { title: "বটিয়াঘাটা", value: "batiaghata" },
      { title: "দাকোপ", value: "dakop" },
      { title: "দিঘলিয়া", value: "dighalia" },
      { title: "দুমুরিয়া", value: "dumuria" },
      { title: "ফুলতলা", value: "phultala" },
      { title: "কয়রা", value: "koyra" },
      { title: "পাইকগাছা", value: "paikgachha" },
      { title: "রূপসা", value: "rupsa" },
      { title: "তেরখাদা", value: "terokhada" },
    ],
  },
  বাগেরহাট: {
    value: "bagerhat",
    upazilas: [
      { title: "বাগেরহাট সদর", value: "bagerhat-sadar" },
      { title: "চিতলমারী", value: "chitalmari" },
      { title: "ফকিরহাট", value: "fakirhat" },
      { title: "কচুয়া", value: "kachua" },
      { title: "মোল্লাহাট", value: "mollahat" },
      { title: "মোংলা", value: "mongla" },
      { title: "মোরেলগঞ্জ", value: "morrelganj" },
      { title: "রামপাল", value: "rampal" },
      { title: "শরণখোলা", value: "sarankhola" },
    ],
  },
  চুয়াডাঙ্গা: {
    value: "chuadanga",
    upazilas: [
      { title: "আলমডাঙ্গা", value: "alamdanga" },
      { title: "চুয়াডাঙ্গা সদর", value: "chuadanga-sadar" },
      { title: "দামুড়হুদা", value: "damurhuda" },
      { title: "জীবননগর", value: "jibannagar" },
    ],
  },
  যশোর: {
    value: "jashore",
    upazilas: [
      { title: "অভয়নগর", value: "abhaynagar" },
      { title: "বাঘারপাড়া", value: "bagherpara" },
      { title: "চৌগাছা", value: "chougachha" },
      { title: "ঝিকরগাছা", value: "jhikargachha" },
      { title: "কেশবপুর", value: "keshabpur" },
      { title: "যশোর সদর", value: "jashore-sadar" },
      { title: "মনিরামপুর", value: "manirampur" },
      { title: "শার্শা", value: "sharsha" },
    ],
  },
  ঝিনাইদহ: {
    value: "jhenaidah",
    upazilas: [
      { title: "হরিণাকুণ্ডু", value: "harinakunda" },
      { title: "ঝিনাইদহ সদর", value: "jhenaidah-sadar" },
      { title: "কালীগঞ্জ", value: "kaliganj" },
      { title: "কোটচাঁদপুর", value: "kotchandpur" },
      { title: "মহেশপুর", value: "maheshpur" },
      { title: "শৈলকূপা", value: "shailkupa" },
    ],
  },
  কুষ্টিয়া: {
    value: "kushtia",
    upazilas: [
      { title: "ভেড়ামারা", value: "bheramara" },
      { title: "দৌলতপুর", value: "daulatpur" },
      { title: "কুষ্টিয়া সদর", value: "kushtia-sadar" },
      { title: "কুমারখালী", value: "kumarkhali" },
      { title: "খোকসা", value: "khoksa" },
      { title: "মিরপুর", value: "mirpur" },
    ],
  },
  মাগুরা: {
    value: "magura",
    upazilas: [
      { title: "মাগুরা সদর", value: "magura-sadar" },
      { title: "মোহাম্মদপুর", value: "mohammadpur" },
      { title: "শালিখা", value: "shalikha" },
      { title: "শ্রীপুর", value: "sreepur" },
    ],
  },
  মেহেরপুর: {
    value: "meherpur",
    upazilas: [
      { title: "গাংনী", value: "gangni" },
      { title: "মেহেরপুর সদর", value: "meherpur-sadar" },
      { title: "মুজিবনগর", value: "mujibnagar" },
    ],
  },
  নড়াইল: {
    value: "narail",
    upazilas: [
      { title: "কালিয়া", value: "kalia" },
      { title: "লোহাগড়া", value: "lohagara" },
      { title: "নড়াইল সদর", value: "narail-sadar" },
    ],
  },
  সাতক্ষীরা: {
    value: "satkhira",
    upazilas: [
      { title: "আশাশুনি", value: "assasuni" },
      { title: "দেবহাটা", value: "debhata" },
      { title: "কলারোয়া", value: "kalaroa" },
      { title: "কালিগঞ্জ", value: "kaliganj" },
      { title: "সাতক্ষীরা সদর", value: "satkhira-sadar" },
      { title: "শ্যামনগর", value: "shyamnagar" },
      { title: "তালা", value: "tala" },
    ],
  },

  // Mymensingh Division
  ময়মনসিংহ: {
    value: "mymensingh",
    upazilas: [
      { title: "ভালুকা", value: "bhaluka" },
      { title: "ধোবাউড়া", value: "dhobaura" },
      { title: "ফুলবাড়ীয়া", value: "fulbaria" },
      { title: "গফরগাঁও", value: "gaffargaon" },
      { title: "গৌরীপুর", value: "gauripur" },
      { title: "হালুয়াঘাট", value: "haluaghat" },
      { title: "ঈশ্বরগঞ্জ", value: "ishwarganj" },
      { title: "ময়মনসিংহ সদর", value: "mymensingh-sadar" },
      { title: "মুক্তাগাছা", value: "muktagachha" },
      { title: "নান্দাইল", value: "nandail" },
      { title: "ফুলপুর", value: "phulpur" },
      { title: "ত্রিশাল", value: "trishal" },
      { title: "তারাকান্দা", value: "tarakanda" },
    ],
  },
  জামালপুর: {
    value: "jamalpur",
    upazilas: [
      { title: "বকশীগঞ্জ", value: "bakshiganj" },
      { title: "দেওয়ানগঞ্জ", value: "dewanganj" },
      { title: "ইসলামপুর", value: "islampur" },
      { title: "জামালপুর সদর", value: "jamalpur-sadar" },
      { title: "মাদারগঞ্জ", value: "madarganj" },
      { title: "মেলান্দাহ", value: "melandaha" },
      { title: "সরিষাবাড়ী", value: "sarishabari" },
    ],
  },
  নেত্রকোণা: {
    value: "netrokona",
    upazilas: [
      { title: "আটপাড়া", value: "atpara" },
      { title: "বারহাট্টা", value: "barhatta" },
      { title: "দুর্গাপুর", value: "durgapur" },
      { title: "খালিয়াজুরী", value: "khaliajuri" },
      { title: "কলমাকান্দা", value: "kalmakanda" },
      { title: "কেন্দুয়া", value: "kenduua" },
      { title: "মদন", value: "madan" },
      { title: "মোহনগঞ্জ", value: "mohanganj" },
      { title: "নেত্রকোণা সদর", value: "netrokona-sadar" },
      { title: "পূর্বধলা", value: "purbadhala" },
    ],
  },
  শেরপুর: {
    value: "sherpur",
    upazilas: [
      { title: "ঝিনাইগাতী", value: "jhenaigati" },
      { title: "নকলা", value: "nakla" },
      { title: "নালিতাবাড়ী", value: "nalitabari" },
      { title: "শেরপুর সদর", value: "sherpur-sadar" },
      { title: "শ্রীবরদী", value: "sribardi" },
    ],
  },

  // Rajshahi Division
  রাজশাহী: {
    value: "rajshahi",
    upazilas: [
      { title: "বাঘা", value: "bagha" },
      { title: "বাগমারা", value: "bagmara" },
      { title: "চারঘাট", value: "charghat" },
      { title: "দুর্গাপুর", value: "durgapur" },
      { title: "গোদাগাড়ী", value: "godagari" },
      { title: "মোহনপুর", value: "mohanpur" },
      { title: "পাবা", value: "paba" },
      { title: "পুঠিয়া", value: "puthia" },
      { title: "তানোর", value: "tanore" },
    ],
  },
  বগুড়া: {
    value: "bogura",
    upazilas: [
      { title: "আদমদীঘি", value: "adamdighi" },
      { title: "বগুড়া সদর", value: "bogura-sadar" },
      { title: "ধুনট", value: "dhunat" },
      { title: "দুপচাঁচিয়া", value: "dupchanchia" },
      { title: "গাবতলী", value: "gabtali" },
      { title: "কাহালু", value: "kahaloo" },
      { title: "নন্দীগ্রাম", value: "nandigram" },
      { title: "সারিয়াকান্দি", value: "sariakandi" },
      { title: "শাজাহানপুর", value: "shajahanpur" },
      { title: "শেরপুর", value: "sherpur" },
      { title: "শিবগঞ্জ", value: "shibganj" },
      { title: "সোনাতলা", value: "sonatala" },
    ],
  },
  চাঁপাইনবাবগঞ্জ: {
    value: "chapainawabganj",
    upazilas: [
      { title: "ভোলাহাট", value: "bholahat" },
      { title: "গোমস্তাপুর", value: "gomastapur" },
      { title: "নাচোল", value: "nachole" },
      { title: "চাঁপাইনবাবগঞ্জ সদর", value: "chapainawabganj-sadar" },
      { title: "শিবগঞ্জ", value: "shibganj" },
    ],
  },
  জয়পুরহাট: {
    value: "joypurhat",
    upazilas: [
      { title: "আক্কেলপুর", value: "akkelpur" },
      { title: "জয়পুরহাট সদর", value: "joypurhat-sadar" },
      { title: "কালাই", value: "kalai" },
      { title: "ক্ষেতলাল", value: "khetlal" },
      { title: "পাঁচবিবি", value: "panchbibi" },
    ],
  },
  নওগাঁ: {
    value: "naogaon",
    upazilas: [
      { title: "আত্রাই", value: "atrai" },
      { title: "বদলগাছী", value: "badalgachhi" },
      { title: "ধামইরহাট", value: "dhamoirhat" },
      { title: "মান্দা", value: "manda" },
      { title: "মহাদেবপুর", value: "mahadeppur" },
      { title: "নওগাঁ সদর", value: "naogaon-sadar" },
      { title: "নিয়ামতপুর", value: "niamatpur" },
      { title: "পত্নীতলা", value: "patnitala" },
      { title: "পোরশা", value: "porsha" },
      { title: "রাণীনগর", value: "raninagar" },
      { title: "সাপাহার", value: "sapahar" },
    ],
  },
  নাটোর: {
    value: "natore",
    upazilas: [
      { title: "বাগাতিপাড়া", value: "bagatipara" },
      { title: "বড়াইগ্রাম", value: "baraigram" },
      { title: "গুরুদাসপুর", value: "gurudaspur" },
      { title: "লালপুর", value: "lalpur" },
      { title: "নাটোর সদর", value: "natore-sadar" },
      { title: "সিংড়া", value: "singra" },
    ],
  },
  পাবনা: {
    value: "pabna",
    upazilas: [
      { title: "আটঘরিয়া", value: "atgharia" },
      { title: "বেড়া", value: "bera" },
      { title: "ভাঙ্গুড়া", value: "bhangura" },
      { title: "চাটমোহর", value: "chatmohar" },
      { title: "ফরিদপুর", value: "faridpur" },
      { title: "ঈশ্বরদী", value: "ishwardi" },
      { title: "পাবনা সদর", value: "pabna-sadar" },
      { title: "সাঁথিয়া", value: "santhia" },
      { title: "সুজানগর", value: "sujanagar" },
    ],
  },
  সিরাজগঞ্জ: {
    value: "sirajganj",
    upazilas: [
      { title: "বেলকুচি", value: "belkuchi" },
      { title: "চৌহালী", value: "chauhali" },
      { title: "কামারখন্দ", value: "kamarkhanda" },
      { title: "কাজিপুর", value: "kazipur" },
      { title: "রায়গঞ্জ", value: "raiganj" },
      { title: "শাহজাদপুর", value: "shahjadpur" },
      { title: "সিরাজগঞ্জ সদর", value: "sirajganj-sadar" },
      { title: "তারাশ", value: "tarash" },
      { title: "উল্লাপাড়া", value: "ullapara" },
    ],
  },

  // Rangpur Division
  রংপুর: {
    value: "rangpur",
    upazilas: [
      { title: "বদরগঞ্জ", value: "badarganj" },
      { title: "গংগাচড়া", value: "gangachhara" },
      { title: "কাউনিয়া", value: "kaunia" },
      { title: "মিঠাপুকুর", value: "mithapukur" },
      { title: "পীরগাছা", value: "pirgachha" },
      { title: "পীরগঞ্জ", value: "pirganj" },
      { title: "রংপুর সদর", value: "rangpur-sadar" },
      { title: "তারাগঞ্জ", value: "taraganj" },
    ],
  },
  দিনাজপুর: {
    value: "dinajpur",
    upazilas: [
      { title: "বিরল", value: "biral" },
      { title: "বিরামপুর", value: "birampur" },
      { title: "বীরগঞ্জ", value: "birganj" },
      { title: "বোচাগঞ্জ", value: "bochaganj" },
      { title: "চিরিরবন্দর", value: "chirirbandar" },
      { title: "ফুলবাড়ী", value: "fulbari" },
      { title: "ঘোড়াঘাট", value: "ghoraghat" },
      { title: "হাকিমপুর", value: "hakimpur" },
      { title: "কাহারোল", value: "kaharole" },
      { title: "খানসামা", value: "khansama" },
      { title: "দিনাজপুর সদর", value: "dinajpur-sadar" },
      { title: "নবাবগঞ্জ", value: "nawabganj" },
      { title: "পার্বতীপুর", value: "parbatipur" },
    ],
  },
  গাইবান্ধা: {
    value: "gaibandha",
    upazilas: [
      { title: "ফুলছড়ি", value: "fulchhari" },
      { title: "গাইবান্ধা সদর", value: "gaibandha-sadar" },
      { title: "গোবিন্দগঞ্জ", value: "gobindaganj" },
      { title: "পলাশবাড়ী", value: "palashbari" },
      { title: "সাদুল্লাপুর", value: "sadullapur" },
      { title: "সাঘাটা", value: "saghata" },
      { title: "সুন্দরগঞ্জ", value: "sundarganj" },
    ],
  },
  কুড়িগ্রাম: {
    value: "kurigram",
    upazilas: [
      { title: "ভুরুঙ্গামারী", value: "bhurungamari" },
      { title: "চর রাজিবপুর", value: "char-rajibpur" },
      { title: "চিলমারী", value: "chilmari" },
      { title: "ফুলবাড়ী", value: "fulbari" },
      { title: "কুড়িগ্রাম সদর", value: "kurigram-sadar" },
      { title: "নাগেশ্বরী", value: "nageshwari" },
      { title: "রাজারহাট", value: "rajarhat" },
      { title: "রৌমারী", value: "roumari" },
      { title: "উলিপুর", value: "ulipur" },
    ],
  },
  লালমনিরহাট: {
    value: "lalmonirhat",
    upazilas: [
      { title: "আদিতমারী", value: "aditmari" },
      { title: "হাতীবান্ধা", value: "hatibandha" },
      { title: "কালীগঞ্জ", value: "kaliganj" },
      { title: "লালমনিরহাট সদর", value: "lalmonirhat-sadar" },
      { title: "পাটগ্রাম", value: "patgram" },
    ],
  },
  নীলফামারী: {
    value: "nilphamari",
    upazilas: [
      { title: "ডিমলা", value: "dimla" },
      { title: "ডোমার", value: "domar" },
      { title: "জলঢাকা", value: "jaldhaka" },
      { title: "কিশোরগঞ্জ", value: "kishoreganj" },
      { title: "নীলফামারী সদর", value: "nilphamari-sadar" },
      { title: "সৈয়দপুর", value: "sayedpur" },
    ],
  },
  পঞ্চগড়: {
    value: "panchagarh",
    upazilas: [
      { title: "আটোয়ারী", value: "atwari" },
      { title: "বোদা", value: "boda" },
      { title: "দেবীগঞ্জ", value: "debiganj" },
      { title: "পঞ্চগড় সদর", value: "panchagarh-sadar" },
      { title: "তেতুলিয়া", value: "tetulia" },
    ],
  },
  ঠাকুরগাঁও: {
    value: "thakurgaon",
    upazilas: [
      { title: "বালিয়াডাঙ্গী", value: "baliadangi" },
      { title: "হরিপুর", value: "haripur" },
      { title: "পীরগঞ্জ", value: "pirganj" },
      { title: "রাণীশংকৈল", value: "ranisankail" },
      { title: "ঠাকুরগাঁও সদর", value: "thakurgaon-sadar" },
    ],
  },

  // Sylhet Division
  সিলেট: {
    value: "sylhet",
    upazilas: [
      { title: "বালাগঞ্জ", value: "balaganj" },
      { title: "বিয়ানীবাজার", value: "beanibazar" },
      { title: "বিশ্বনাথ", value: "bishwanath" },
      { title: "কোম্পানীগঞ্জ", value: "companionganj" },
      { title: "ফেঞ্চুগঞ্জ", value: "fenchuganj" },
      { title: "গোলাপগঞ্জ", value: "golapganj" },
      { title: "গোয়াইনঘাট", value: "gowainghat" },
      { title: "জৈন্তাপুর", value: "jaintapur" },
      { title: "কানাইঘাট", value: "kanaighat" },
      { title: "সিলেট সদর", value: "sylhet-sadar" },
      { title: "জকিগঞ্জ", value: "zakiganj" },
    ],
  },
  হবিগঞ্জ: {
    value: "habiganj",
    upazilas: [
      { title: "আজমিরীগঞ্জ", value: "ajmiriganj" },
      { title: "বাহুবল", value: "bahubal" },
      { title: "বানিয়াচং", value: "baniyachong" },
      { title: "চুনারুঘাট", value: "chunarughat" },
      { title: "হবিগঞ্জ সদর", value: "habiganj-sadar" },
      { title: "লাখাই", value: "lakhai" },
      { title: "মাধবপুর", value: "madhabpur" },
      { title: "নবীগঞ্জ", value: "nabiganj" },
    ],
  },
  মৌলভীবাজার: {
    value: "moulvibazar",
    upazilas: [
      { title: "বড়লেখা", value: "barlekha" },
      { title: "জুড়ী", value: "juri" },
      { title: "কমলগঞ্জ", value: "kamalganj" },
      { title: "কুলাউড়া", value: "kulaura" },
      { title: "মৌলভীবাজার সদর", value: "moulvibazar-sadar" },
      { title: "রাজনগর", value: "rajnagar" },
      { title: "শ্রীমঙ্গল", value: "sreemangal" },
    ],
  },
  সুনামগঞ্জ: {
    value: "sunamganj",
    upazilas: [
      { title: "বিশ্বম্ভরপুর", value: "bishwambharpur" },
      { title: "ছাতক", value: "chhatak" },
      { title: "দেরাই", value: "derai" },
      { title: "ধর্মপাশা", value: "dharmapasha" },
      { title: "দোয়ারাবাজার", value: "dowarabazar" },
      { title: "জগন্নাথপুর", value: "jagannathpur" },
      { title: "জামালগঞ্জ", value: "jamalganj" },
      { title: "শাল্লা", value: "shalla" },
      { title: "সুনামগঞ্জ সদর", value: "sunamganj-sadar" },
      { title: "তাহিরপুর", value: "tahirpur" },
      { title: "শান্তিগঞ্জ", value: "shantiganj" },
      { title: "মধ্যনগর", value: "madhyanagar" },
    ],
  },
};
