export const searchingFilters = {
  biodataType: [
    { id: "GROOM", title: "পাত্রের বায়োডাটা" },
    { id: "BRIDE", title: "পাত্রীর বায়োডাটা" },
  ],
  maritalStatus: [
    { id: "unmarried", title: "অবিবাহিত", for: "both" },
    { id: "married", title: "বিবাহিত", for: "both" },
    { id: "divorced", title: "ডিভোর্সড", for: "both" },
    { id: "widowed_male", title: "বিপত্নীক", for: "BRIDE" },
    { id: "widowed_female", title: "বিধবা", for: "GROOM" },
  ],
  skinTones: [
    { id: "dark", title: "গাঢ় ত্বক", for: "both" },
    { id: "medium", title: "শ্যামলা", for: "both" },
    { id: "light_medium", title: "উজ্জ্বল শ্যামলা", for: "both" },
    { id: "fair", title: "ফর্সা", for: "both" },
    { id: "very_fair", title: "উজ্জ্বল ফর্সা", for: "both" },
  ],
  permanentAddress: [
    { id: "bangladesh", title: "বাংলাদেশ", for: "both" },
    { id: "foreign", title: "বিদেশ", for: "both" },
  ],
  currentAddress: [
    { id: "bangladesh", title: "বাংলাদেশ", for: "both" },
    { id: "foreign", title: "বিদেশ", for: "both" },
  ],
  religiousLifestyle: [
    { id: "devout", title: "পূর্ণ ধার্মিক/প্র্যাক্টিসিং", for: "both" },
    { id: "practicing", title: "প্রাক্টিসিংয়ের চেষ্টারত", for: "both" },
    { id: "general", title: "জেনারেল/নন-প্রাক্টিসিং", for: "both" },
  ],
  occupation: [
    { id: "business", title: "ব্যবসা", for: "both" },
    { id: "govt_job", title: "সরকারি চাকরিজীবী", for: "both" },
    { id: "private_job", title: "বেসরকারি চাকরিজীবী", for: "both" },
    { id: "home_tutor", title: "হোম টিউটর", for: "both" },
    { id: "teacher", title: "শিক্ষক/শিক্ষিকা", for: "both" },
    { id: "lawyer", title: "আইনজীবী", for: "both" },
    { id: "engineer", title: "ইঞ্জিনিয়ার", for: "both" },
    { id: "doctor", title: "ডাক্তার", for: "both" },
    { id: "vet_doctor", title: "ভেটেরিনারি ডাক্তার", for: "both" },
    { id: "nurse", title: "নার্স", for: "both" },
    { id: "pharmacist", title: "ফার্মাসিস্ট", for: "both" },
    { id: "paramedic", title: "প্যারামেডিক", for: "both" },
    { id: "therapist", title: "থেরাপিস্ট", for: "both" },
    { id: "medical_technologist", title: "মেডিকেল টেকনোলজিস্ট", for: "both" },
    {
      id: "medical_assistant",
      title: "মেডিক্যাল অ্যাসিস্ট্যান্ট",
      for: "both",
    },
    { id: "military_job", title: "সামরিক জব", for: "both" },
    { id: "paramilitary_job", title: "আধা সামরিক জব", for: "both" },
    { id: "imam", title: "ইমাম", for: "both" },
    { id: "muezzin", title: "মুয়াজ্জিন", for: "both" },
    { id: "pilot", title: "পাইলট", for: "both" },
    { id: "freelancer", title: "ফ্রিল্যান্সার", for: "both" },
    { id: "student", title: "শিক্ষার্থী", for: "both" },
    { id: "mbbs_bds_student", title: "MBBS/BDS শিক্ষার্থী", for: "both" },
    { id: "expatriate_job", title: "প্রবাসী-প্রবাস জব", for: "both" },
    { id: "manual_labor", title: "মিস্ত্রী/কায়িক শ্রম", for: "both" },
    { id: "agriculture", title: "কৃষিকাজ", for: "both" },
    { id: "jobless", title: "চাকরির সন্ধানরত/বেকার", for: "both" },
    { id: "family_property", title: "পারিবারিক সম্পত্তি", for: "both" },
    { id: "no_occupation", title: "পেশা নেই/কর্মহীন", for: "both" },
    { id: "other_occupation", title: "অন্যান্য", for: "both" },
  ],
  education: [
    { id: "qawmi", title: "কওমি", for: "both" },
    { id: "alia", title: "আলিয়া", for: "both" },
    { id: "diploma", title: "ডিপ্লোমা", for: "both" },
    { id: "bachelor", title: "স্নাতক", for: "both" },
    { id: "masters", title: "স্নাতকোত্তর", for: "both" },
    { id: "doctoral", title: "ডক্টরাল", for: "both" },
    { id: "bcs", title: "বি.সি.এস (BCS)", for: "both" },
    { id: "medical", title: "মেডিকেল", for: "both" },
    { id: "defense", title: "ডিফেন্স", for: "both" },
    { id: "police_law", title: "পুলিশ/আইন-শৃঙ্খলা বাহিনী", for: "both" },
    { id: "aviation", title: "এভিয়েশন", for: "both" },
  ],
  religiousEducation: [
    { id: "hafiz_male", title: "হাফেজ", for: "BRIDE" },
    { id: "hafiza_female", title: "হাফেজা", for: "GROOM" },
    { id: "maulana_male", title: "মাওলানা", for: "BRIDE" },
    { id: "alema_female", title: "আলেমা", for: "GROOM" },
    { id: "mufti_male", title: "মুফতি", for: "BRIDE" },
    { id: "muftia_female", title: "মুফতিয়া", for: "GROOM" },
    { id: "muhaddis_male", title: "মুহাদ্দিস", for: "BRIDE" },
    { id: "muhaddisa_female", title: "মুহাদ্দিসা", for: "GROOM" },
    { id: "mufassir", title: "মুফাসসির", for: "both" },
    { id: "faqih", title: "ফকিহ", for: "both" },
    { id: "daee_male", title: "দা'য়ী", for: "BRIDE" },
    { id: "daiya_female", title: "দাঈয়া", for: "GROOM" },
    { id: "adib", title: "আদিব", for: "both" },
    { id: "qari_male", title: "ক্বারী", for: "BRIDE" },
    { id: "qaria_female", title: "ক্বারিয়া", for: "GROOM" },
    { id: "talib_quran", title: "তালিবে কুরআন", for: "both" },
    { id: "tajwid_student", title: "তাজবীদ শিক্ষার্থী", for: "both" },
    { id: "muallim_talim", title: "মুয়াল্লিমুন ফি তালিম", for: "both" },
    { id: "islamic_scholar", title: "ইসলামিক স্কলার", for: "both" },
  ],
  familyBackgrounds: [
    { id: "upper_class", title: "উচ্চবিত্ত", for: "both" },
    { id: "upper_middle", title: "উচ্চ মধ্যবিত্ত", for: "both" },
    { id: "middle", title: "মধ্যবিত্ত", for: "both" },
    { id: "lower_middle", title: "নিম্ন মধ্যবিত্ত", for: "both" },
    { id: "lower_class", title: "নিম্নবিত্ত", for: "both" },
  ],
  madhhab: [
    { id: "hanafi", title: "হানাফি", for: "both" },
    { id: "salafi", title: "সালাফি/আহলে হাদিস", for: "both" },
    { id: "shafi", title: "শাফেঈ", for: "both" },
    { id: "maliki", title: "মালিকী", for: "both" },
    { id: "hambali", title: "হাম্বলি", for: "both" },
    { id: "other_madhhab", title: "অন্যান্য", for: "both" },
    { id: "unknown_madhhab", title: "জানা নেই", for: "both" },
  ],
  bloodGroup: [
    { id: "A+", title: "A+", for: "both" },
    { id: "B+", title: "B+", for: "both" },
    { id: "A-", title: "A-", for: "both" },
    { id: "B-", title: "B-", for: "both" },
    { id: "AB+", title: "AB+", for: "both" },
    { id: "AB-", title: "AB-", for: "both" },
    { id: "O+", title: "O+", for: "both" },
    { id: "O-", title: "O-", for: "both" },
  ],
  specialCategory: [
    { id: "expatriate", title: "প্রবাসী", for: "both" },
    {
      id: "foreign_citizen",
      title: "ফরেইন সিটিজেন",
      for: "both",
    },
    {
      id: "social_worker",
      title: "সমাজ সেবক",
      for: "both",
    },
    { id: "tabligh", title: "তাবলীগ", for: "both" },
    {
      id: "deen_service",
      title: "দ্বীনের খেদমতকারী",
      for: "both",
    },
    { id: "new_muslim", title: "নওমুসলিম", for: "both" },
    {
      id: "disabled",
      title: "প্রতিবন্ধী",
      for: "both",
    },
    { id: "orphan", title: "এতিম", for: "both" },
    {
      id: "infertile",
      title: "বন্ধ্যা/ইনফার্টিলিটি",
      for: "both",
    },
    {
      id: "short_divorced",
      title: "শর্ট ডিভোর্সি",
      for: "both",
    },
    {
      id: "single_father",
      title: "সিঙ্গেল ফাদার",
      for: "male",
    },
    {
      id: "single_mother",
      title: "সিঙ্গেল মাদার",
      for: "female",
    },
    {
      id: "short_height",
      title: "স্বল্প উচ্চতার",
      for: "both",
    },
    { id: "older_age", title: "বয়সে বেশি", for: "both" },
    {
      id: "urban_resident",
      title: "শহরে বসবাসকারী",
      for: "both",
    },
    {
      id: "rural_resident",
      title: "গ্রামে বসবাসকারী",
      for: "both",
    },
    {
      id: "allow_wife_job",
      title: "স্ত্রীকে চাকরি/ব্যবসা করতে দিবে",
      for: "male",
    },
    {
      id: "allow_wife_study",
      title: "স্ত্রীকে পড়াশোনা করতে দিবে",
      for: "male",
    },
    {
      id: "employed_female",
      title: "চাকরিজীবী",
      for: "female",
    },
    {
      id: "job_interest_post_marriage",
      title: "বিয়ের পর চাকরি/ব্যাবসায় আগ্রহী",
      for: "female",
    },
    {
      id: "masna_interest",
      title: "মাসনায় আগ্রহী",
      for: "female",
    },
  ],
};

export const beingSearchedFilters = {
  selfBiodataType: [
    { id: "BRIDE", title: "আমি পাত্র" },
    {
      id: "GROOM",
      title: "আমি পাত্রী",
    },
  ],
  specialCategory: [
    {
      id: "expatriate",
      title: "আমি একজন প্রবাসী",
      for: "both",
    },
    {
      id: "foreign_citizen",
      title: "আমার ফরেইন সিটিজেনশিপ আছে",
      for: "both",
    },
    {
      id: "short_divorced",
      title: "আমি শর্ট ডিভোর্সি বা ডিভোর্সড",
      for: "both",
    },
    {
      id: "widowed_male",
      title: "আমি বিপত্নীক",
      for: "BRIDE",
    },
    {
      id: "widowed_female",
      title: "আমি বিধবা",
      for: "GROOM",
    },
    {
      id: "single_father",
      title: "আমি সিঙ্গেল ফাদার (সন্তান আছে কিন্তু মা নেই বা দায়িত্বে নেই)",
      for: "BRIDE",
    },
    {
      id: "single_mother",
      title: "আমি সিঙ্গেল মাদার (সন্তান আছে কিন্তু বাবা নেই বা দায়িত্বে নেই)",
      for: "GROOM",
    },
    {
      id: "second_marriage_male",
      title: "আমি মাসনা বা দ্বিতীয় বিবাহে আগ্রহী",
      for: "BRIDE",
    },
    {
      id: "second_marriage_female",
      title: "আমি দ্বিতীয় স্ত্রী বা মাসনা হতে আগ্রহী",
      for: "GROOM",
    },
    {
      id: "short_height",
      title: "আমি স্বল্প উচ্চতার",
      for: "both",
    },
    {
      id: "older_age",
      title: "আমি বয়সে বেশি",
      for: "both",
    },
    {
      id: "village_resident",
      title: "আমি গ্রামে বসবাসকারী",
      for: "both",
    },
    {
      id: "dark_complexion",
      title: "আমার গায়ের বর্ণ গাঢ়",
      for: "GROOM",
    },
    {
      id: "infertility",
      title: "আমি বন্ধ্যাত্ব সমস্যায় ভুগছি",
      for: "both",
    },
    {
      id: "new_muslim",
      title: "আমি একজন নওমুসলিম",
      for: "both",
    },
    { id: "orphan", title: "আমি এতিম", for: "both" },
    {
      id: "disabled",
      title: "আমি প্রতিবন্ধী",
      for: "both",
    },
    {
      id: "religious_service",
      title: "আমি দ্বীনের খেদমতে আছি",
      for: "both",
    },
    {
      id: "tabligh",
      title: "আমি তাবলীগ এর সাথে যুক্ত",
      for: "both",
    },
    {
      id: "social_worker",
      title: "আমি একজন সমাজ সেবক",
      for: "both",
    },
    {
      id: "employed",
      title: "আমি একজন চাকরিজীবী",
      for: "both",
    },
    {
      id: "post_marriage_job",
      title: "আমি বিয়ের পর চাকরি / ব্যাবসায় আগ্রহী",
      for: "both",
    },
    {
      id: "post_marriage_study",
      title: "আমি বিয়ের পর পড়াশোনা করতে আগ্রহী",
      for: "both",
    },
  ],
};
