export const searchingFilters = {
  biodataType: [
    { id: "male", value: "পাত্রের বায়োডাটা", label: "পাত্রের বায়োডাটা" },
    { id: "female", value: "পাত্রীর বায়োডাটা", label: "পাত্রীর বায়োডাটা" },
  ],
  maritalStatus: [
    { id: "unmarried", value: "অবিবাহিত", label: "অবিবাহিত", gender: "both" },
    { id: "married", value: "বিবাহিত", label: "বিবাহিত", gender: "both" },
    { id: "divorced", value: "ডিভোর্সড", label: "ডিভোর্সড", gender: "both" },
    {
      id: "widowed_male",
      value: "বিপত্নীক",
      label: "বিপত্নীক",
      gender: "male",
    },
    { id: "widowed_female", value: "বিধবা", label: "বিধবা", gender: "female" },
  ],
  complexion: [
    { id: "dark", value: "গাঢ় ত্বক", label: "গাঢ় ত্বক", gender: "both" },
    { id: "medium", value: "শ্যামলা", label: "শ্যামলা", gender: "both" },
    {
      id: "light_medium",
      value: "উজ্জ্বল শ্যামলা",
      label: "উজ্জ্বল শ্যামলা",
      gender: "both",
    },
    { id: "fair", value: "ফর্সা", label: "ফর্সা", gender: "both" },
    {
      id: "very_fair",
      value: "উজ্জ্বল ফর্সা",
      label: "উজ্জ্বল ফর্সা",
      gender: "both",
    },
  ],
  permanentAddress: [
    { id: "bangladesh", value: "বাংলাদেশ", label: "বাংলাদেশ", gender: "both" },
    { id: "abroad", value: "বিদেশ", label: "বিদেশ", gender: "both" },
  ],
  currentAddress: [
    { id: "bangladesh", value: "বাংলাদেশ", label: "বাংলাদেশ", gender: "both" },
    { id: "abroad", value: "বিদেশ", label: "বিদেশ", gender: "both" },
  ],
  religiousLifestyle: [
    {
      id: "general",
      value: "জেনারেল/নন-প্রাক্টিসিং",
      label: "জেনারেল/নন-প্রাক্টিসিং",
      gender: "both",
    },
    {
      id: "practicing",
      value: "প্রাক্টিসিংয়ের চেষ্টারত",
      label: "প্রাক্টিসিংয়ের চেষ্টারত",
      gender: "both",
    },
    {
      id: "devout",
      value: "পূর্ণ ধার্মিক/প্র্যাক্টিসিং",
      label: "পূর্ণ ধার্মিক/প্র্যাক্টিসিং",
      gender: "both",
    },
  ],
  occupation: [
    { id: "business", value: "ব্যবসা", label: "ব্যবসা", gender: "both" },
    {
      id: "govt_job",
      value: "সরকারি চাকরিজীবী",
      label: "সরকারি চাকরিজীবী",
      gender: "both",
    },
    {
      id: "private_job",
      value: "বেসরকারি চাকরিজীবী",
      label: "বেসরকারি চাকরিজীবী",
      gender: "both",
    },
    {
      id: "home_tutor",
      value: "হোম টিউটর",
      label: "হোম টিউটর",
      gender: "both",
    },
    {
      id: "teacher",
      value: "শিক্ষক/শিক্ষিকা",
      label: "শিক্ষক/শিক্ষিকা",
      gender: "both",
    },
    { id: "lawyer", value: "আইনজীবী", label: "আইনজীবী", gender: "both" },
    {
      id: "engineer",
      value: "ইঞ্জিনিয়ার",
      label: "ইঞ্জিনিয়ার",
      gender: "both",
    },
    { id: "doctor", value: "ডাক্তার", label: "ডাক্তার", gender: "both" },
    {
      id: "vet_doctor",
      value: "ভেটেরিনারি ডাক্তার",
      label: "ভেটেরিনারি ডাক্তার",
      gender: "both",
    },
    { id: "nurse", value: "নার্স", label: "নার্স", gender: "both" },
    {
      id: "pharmacist",
      value: "ফার্মাসিস্ট",
      label: "ফার্মাসিস্ট",
      gender: "both",
    },
    {
      id: "paramedic",
      value: "প্যারামেডিক",
      label: "প্যারামেডিক",
      gender: "both",
    },
    { id: "therapist", value: "থেরাপিস্ট", label: "থেরাপিস্ট", gender: "both" },
    {
      id: "medical_technologist",
      value: "মেডিকেল টেকনোলজিস্ট",
      label: "মেডিকেল টেকনোলজিস্ট",
      gender: "both",
    },
    {
      id: "medical_assistant",
      value: "মেডিক্যাল অ্যাসিস্ট্যান্ট",
      label: "মেডিক্যাল অ্যাসিস্ট্যান্ট",
      gender: "both",
    },
    {
      id: "military_job",
      value: "সামরিক জব",
      label: "সামরিক জব",
      gender: "both",
    },
    {
      id: "civilian_job",
      value: "বেসামরিক জব",
      label: "বেসামরিক জব",
      gender: "both",
    },
    {
      id: "paramilitary_job",
      value: "আধা সামরিক জব",
      label: "আধা সামরিক জব",
      gender: "both",
    },
    { id: "imam", value: "ইমাম", label: "ইমাম", gender: "both" },
    { id: "muezzin", value: "মুয়াজ্জিন", label: "মুয়াজ্জিন", gender: "both" },
    { id: "pilot", value: "পাইলট", label: "পাইলট", gender: "both" },
    {
      id: "freelancer",
      value: "ফ্রিল্যান্সার",
      label: "ফ্রিল্যান্সার",
      gender: "both",
    },
    { id: "student", value: "শিক্ষার্থী", label: "শিক্ষার্থী", gender: "both" },
    {
      id: "mbbs_bds_student",
      value: "MBBS/BDS শিক্ষার্থী",
      label: "MBBS/BDS শিক্ষার্থী",
      gender: "both",
    },
    {
      id: "expatriate_job",
      value: "প্রবাসী-প্রবাস জব",
      label: "প্রবাসী-প্রবাস জব",
      gender: "both",
    },
    {
      id: "manual_labor",
      value: "মিস্ত্রী/কায়িক শ্রম",
      label: "মিস্ত্রী/কায়িক শ্রম",
      gender: "both",
    },
    { id: "agriculture", value: "কৃষিকাজ", label: "কৃষিকাজ", gender: "both" },
    {
      id: "jobless",
      value: "চাকরির সন্ধানরত/বেকার",
      label: "চাকরির সন্ধানরত/বেকার",
      gender: "both",
    },
    {
      id: "family_property",
      value: "পারিবারিক সম্পত্তি",
      label: "পারিবারিক সম্পত্তি",
      gender: "both",
    },
    {
      id: "no_occupation",
      value: "পেশা নেই/কর্মহীন",
      label: "পেশা নেই/কর্মহীন",
      gender: "both",
    },
    {
      id: "other_occupation",
      value: "অন্যান্য",
      label: "অন্যান্য",
      gender: "both",
    },
  ],
  education: [
    { id: "qawmi", value: "কওমি", label: "কওমি", gender: "both" },
    { id: "alia", value: "আলিয়া", label: "আলিয়া", gender: "both" },
    { id: "diploma", value: "ডিপ্লোমা", label: "ডিপ্লোমা", gender: "both" },
    { id: "bachelor", value: "স্নাতক", label: "স্নাতক", gender: "both" },
    {
      id: "masters",
      value: "স্নাতকোত্তর",
      label: "স্নাতকোত্তর",
      gender: "both",
    },
    { id: "doctoral", value: "ডক্টরাল", label: "ডক্টরাল", gender: "both" },
    {
      id: "bcs",
      value: "বি.সি.এস (BCS)",
      label: "বি.সি.এস (BCS)",
      gender: "both",
    },
    { id: "medical", value: "মেডিকেল", label: "মেডিকেল", gender: "both" },
    { id: "defense", value: "ডিফেন্স", label: "ডিফেন্স", gender: "both" },
    {
      id: "police_law",
      value: "পুলিশ/আইন-শৃঙ্খলা বাহিনী",
      label: "পুলিশ/আইন-শৃঙ্খলা বাহিনী",
      gender: "both",
    },
    { id: "aviation", value: "এভিয়েশন", label: "এভিয়েশন", gender: "both" },
  ],
  religiousEducation: [
    { id: "hafiz_male", value: "হাফেজ", label: "হাফেজ", gender: "male" },
    { id: "hafiza_female", value: "হাফেজা", label: "হাফেজা", gender: "female" },
    { id: "maulana_male", value: "মাওলানা", label: "মাওলানা", gender: "male" },
    { id: "alema_female", value: "আলেমা", label: "আলেমা", gender: "female" },
    { id: "mufti_male", value: "মুফতি", label: "মুফতি", gender: "male" },
    {
      id: "muftia_female",
      value: "মুফতিয়া",
      label: "মুফতিয়া",
      gender: "female",
    },
    {
      id: "muhaddis_male",
      value: "মুহাদ্দিস",
      label: "মুহাদ্দিস",
      gender: "male",
    },
    {
      id: "muhaddisa_female",
      value: "মুহাদ্দিসা",
      label: "মুহাদ্দিসা",
      gender: "female",
    },
    { id: "mufassir", value: "মুফাসসির", label: "মুফাসসির", gender: "both" },
    { id: "faqih", value: "ফকিহ", label: "ফকিহ", gender: "both" },
    { id: "daee_male", value: "দা'য়ী", label: "দা'য়ী", gender: "male" },
    { id: "daiya_female", value: "দাঈয়া", label: "দাঈয়া", gender: "female" },
    { id: "adib", value: "আদিব", label: "আদিব", gender: "both" },
    { id: "qari_male", value: "ক্বারী", label: "ক্বারী", gender: "male" },
    {
      id: "qaria_female",
      value: "ক্বারিয়া",
      label: "ক্বারিয়া",
      gender: "female",
    },
    {
      id: "talib_quran",
      value: "তালিবে কুরআন",
      label: "তালিবে কুরআন",
      gender: "both",
    },
    {
      id: "tajwid_student",
      value: "তাজবীদ শিক্ষার্থী",
      label: "তাজবীদ শিক্ষার্থী",
      gender: "both",
    },
    {
      id: "muallim_talim",
      value: "মুয়াল্লিমুন ফি তালিম",
      label: "মুয়াল্লিমুন ফি তালিম",
      gender: "both",
    },
    {
      id: "islamic_scholar",
      value: "ইসলামিক স্কলার",
      label: "ইসলামিক স্কলার",
      gender: "both",
    },
  ],
  familyStatus: [
    {
      id: "upper_class",
      value: "উচ্চবিত্ত",
      label: "উচ্চবিত্ত",
      gender: "both",
    },
    {
      id: "upper_middle",
      value: "উচ্চ মধ্যবিত্ত",
      label: "উচ্চ মধ্যবিত্ত",
      gender: "both",
    },
    { id: "middle", value: "মধ্যবিত্ত", label: "মধ্যবিত্ত", gender: "both" },
    {
      id: "lower_middle",
      value: "নিম্ন মধ্যবিত্ত",
      label: "নিম্ন মধ্যবিত্ত",
      gender: "both",
    },
    {
      id: "lower_class",
      value: "নিম্নবিত্ত",
      label: "নিম্নবিত্ত",
      gender: "both",
    },
  ],
  madhhab: [
    { id: "hanafi", value: "হানাফি", label: "হানাফি", gender: "both" },
    {
      id: "salafi",
      value: "সালাফি/আহলে হাদিস",
      label: "সালাফি/আহলে হাদিস",
      gender: "both",
    },
    { id: "shafi", value: "শাফেঈ", label: "শাফেঈ", gender: "both" },
    { id: "maliki", value: "মালিকী", label: "মালিকী", gender: "both" },
    { id: "hambali", value: "হাম্বলি", label: "হাম্বলি", gender: "both" },
    {
      id: "other_madhhab",
      value: "অন্যান্য",
      label: "অন্যান্য",
      gender: "both",
    },
    {
      id: "unknown_madhhab",
      value: "জানা নেই",
      label: "জানা নেই",
      gender: "both",
    },
  ],
  bloodGroup: [
    { id: "A+", value: "A+", label: "A+", gender: "both" },
    { id: "B+", value: "B+", label: "B+", gender: "both" },
    { id: "A-", value: "A-", label: "A-", gender: "both" },
    { id: "B-", value: "B-", label: "B-", gender: "both" },
    { id: "AB+", value: "AB+", label: "AB+", gender: "both" },
    { id: "AB-", value: "AB-", label: "AB-", gender: "both" },
    { id: "O+", value: "O+", label: "O+", gender: "both" },
    { id: "O-", value: "O-", label: "O-", gender: "both" },
  ],
  specialCategory: [
    { id: "expatriate", value: "প্রবাসী", label: "প্রবাসী", gender: "both" },
    {
      id: "foreign_citizen",
      value: "ফরেইন সিটিজেন",
      label: "ফরেইন সিটিজেন",
      gender: "both",
    },
    {
      id: "social_worker",
      value: "সমাজ সেবক",
      label: "সমাজ সেবক",
      gender: "both",
    },
    { id: "tabligh", value: "তাবলীগ", label: "তাবলীগ", gender: "both" },
    {
      id: "deen_service",
      value: "দ্বীনের খেদমতকারী",
      label: "দ্বীনের খেদমতকারী",
      gender: "both",
    },
    { id: "new_muslim", value: "নওমুসলিম", label: "নওমুসলিম", gender: "both" },
    {
      id: "disabled",
      value: "প্রতিবন্ধী",
      label: "প্রতিবন্ধী",
      gender: "both",
    },
    { id: "orphan", value: "এতিম", label: "এতিম", gender: "both" },
    {
      id: "infertile",
      value: "বন্ধ্যা/ইনফার্টিলিটি",
      label: "বন্ধ্যা/ইনফার্টিলিটি",
      gender: "both",
    },
    {
      id: "short_divorced",
      value: "শর্ট ডিভোর্সি",
      label: "শর্ট ডিভোর্সি",
      gender: "both",
    },
    {
      id: "single_father",
      value: "সিঙ্গেল ফাদার",
      label: "সিঙ্গেল ফাদার",
      gender: "male",
    },
    {
      id: "single_mother",
      value: "সিঙ্গেল মাদার",
      label: "সিঙ্গেল মাদার",
      gender: "female",
    },
    {
      id: "short_height",
      value: "স্বল্প উচ্চতার",
      label: "স্বল্প উচ্চতার",
      gender: "both",
    },
    { id: "older_age", value: "বয়সে বেশি", label: "বয়সে বেশি", gender: "both" },
    {
      id: "urban_resident",
      value: "শহরে বসবাসকারী",
      label: "শহরে বসবাসকারী",
      gender: "both",
    },
    {
      id: "rural_resident",
      value: "গ্রামে বসবাসকারী",
      label: "গ্রামে বসবাসকারী",
      gender: "both",
    },
    {
      id: "allow_wife_job",
      value: "স্ত্রীকে চাকরি/ব্যবসা করতে দিবে",
      label: "স্ত্রীকে চাকরি/ব্যবসা করতে দিবে",
      gender: "male",
    },
    {
      id: "allow_wife_study",
      value: "স্ত্রীকে পড়াশোনা করতে দিবে",
      label: "স্ত্রীকে পড়াশোনা করতে দিবে",
      gender: "male",
    },
    {
      id: "employed_female",
      value: "চাকরিজীবী",
      label: "চাকরিজীবী",
      gender: "female",
    },
    {
      id: "job_interest_post_marriage",
      value: "বিয়ের পর চাকরি/ব্যাবসায় আগ্রহী",
      label: "বিয়ের পর চাকরি/ব্যাবসায় আগ্রহী",
      gender: "female",
    },
    {
      id: "masna_interest",
      value: "মাসনায় আগ্রহী",
      label: "মাসনায় আগ্রহী",
      gender: "female",
    },
  ],
};

export const beingSearchedFilters = {
  selfBiodataType: [
    { id: "male", value: "আমি পাত্র", label: "আমি পাত্র", gender: "male" },
    {
      id: "female",
      value: "আমি পাত্রী",
      label: "আমি পাত্রী",
      gender: "female",
    },
  ],
  specialCategory: [
    {
      id: "expatriate",
      value: "আমি একজন প্রবাসী",
      label: "আমি একজন প্রবাসী",
      gender: "both",
    },
    {
      id: "foreign_citizen",
      value: "আমার ফরেইন সিটিজেনশিপ আছে",
      label: "আমার ফরেইন সিটিজেনশিপ আছে",
      gender: "both",
    },
    {
      id: "short_divorced",
      value: "আমি শর্ট ডিভোর্সি বা ডিভোর্সড",
      label: "আমি শর্ট ডিভোর্সি বা ডিভোর্সড",
      gender: "both",
    },
    {
      id: "widowed_male",
      value: "আমি বিপত্নীক",
      label: "আমি বিপত্নীক",
      gender: "male",
    },
    {
      id: "widowed_female",
      value: "আমি বিধবা",
      label: "আমি বিধবা",
      gender: "female",
    },
    {
      id: "single_father",
      value: "আমি সিঙ্গেল ফাদার (সন্তান আছে কিন্তু মা নেই বা দায়িত্বে নেই)",
      label: "আমি সিঙ্গেল ফাদার (সন্তান আছে কিন্তু মা নেই বা দায়িত্বে নেই)",
      gender: "male",
    },
    {
      id: "single_mother",
      value: "আমি সিঙ্গেল মাদার (সন্তান আছে কিন্তু বাবা নেই বা দায়িত্বে নেই)",
      label: "আমি সিঙ্গেল মাদার (সন্তান আছে কিন্তু বাবা নেই বা দায়িত্বে নেই)",
      gender: "female",
    },
    {
      id: "second_marriage_male",
      value: "আমি মাসনা বা দ্বিতীয় বিবাহে আগ্রহী",
      label: "আমি মাসনা বা দ্বিতীয় বিবাহে আগ্রহী",
      gender: "male",
    },
    {
      id: "second_marriage_female",
      value: "আমি দ্বিতীয় স্ত্রী বা মাসনা হতে আগ্রহী",
      label: "আমি দ্বিতীয় স্ত্রী বা মাসনা হতে আগ্রহী",
      gender: "female",
    },
    {
      id: "short_height",
      value: "আমি স্বল্প উচ্চতার",
      label: "আমি স্বল্প উচ্চতার",
      gender: "both",
    },
    {
      id: "older_age",
      value: "আমি বয়সে বেশি",
      label: "আমি বয়সে বেশি",
      gender: "both",
    },
    {
      id: "village_resident",
      value: "আমি গ্রামে বসবাসকারী",
      label: "আমি গ্রামে বসবাসকারী",
      gender: "both",
    },
    {
      id: "dark_complexion",
      value: "আমার গায়ের বর্ণ গাঢ়",
      label: "আমার গায়ের বর্ণ গাঢ়",
      gender: "female",
    },
    {
      id: "infertility",
      value: "আমি বন্ধ্যাত্ব সমস্যায় ভুগছি",
      label: "আমি বন্ধ্যাত্ব সমস্যায় ভুগছি",
      gender: "both",
    },
    {
      id: "new_muslim",
      value: "আমি একজন নওমুসলিম",
      label: "আমি একজন নওমুসলিম",
      gender: "both",
    },
    { id: "orphan", value: "আমি এতিম", label: "আমি এতিম", gender: "both" },
    {
      id: "disabled",
      value: "আমি প্রতিবন্ধী",
      label: "আমি প্রতিবন্ধী",
      gender: "both",
    },
    {
      id: "religious_service",
      value: "আমি দ্বীনের খেদমতে আছি",
      label: "আমি দ্বীনের খেদমতে আছি",
      gender: "both",
    },
    {
      id: "tabligh",
      value: "আমি তাবলীগ এর সাথে যুক্ত",
      label: "আমি তাবলীগ এর সাথে যুক্ত",
      gender: "both",
    },
    {
      id: "social_worker",
      value: "আমি একজন সমাজ সেবক",
      label: "আমি একজন সমাজ সেবক",
      gender: "both",
    },
    {
      id: "employed",
      value: "আমি একজন চাকরিজীবী",
      label: "আমি একজন চাকরিজীবী",
      gender: "female",
    },
    {
      id: "post_marriage_job",
      value: "আমি বিয়ের পর চাকরি / ব্যাবসায় আগ্রহী",
      label: "আমি বিয়ের পর চাকরি / ব্যাবসায় আগ্রহী",
      gender: "female",
    },
    {
      id: "post_marriage_study",
      value: "আমি বিয়ের পর পড়াশোনা করতে আগ্রহী",
      label: "আমি বিয়ের পর পড়াশোনা করতে আগ্রহী",
      gender: "female",
    },
  ],
};
